package:
  name: nbextensions
  version: "master"

source:
  git_url: git@github.com:benvarkey/IPython-notebook-extensions.git
  git_tag: master

build:
  script: python setup.py install
  
requirements:
  build:
    - ipython >=4
    - jupyter_client
    - jupyter_core
    - notebook
    - nbconvert
    - nbformat
    - python
    - traitlets
    - psutil

  run:
    - ipython >=4
    - jupyter_client
    - jupyter_core
    - notebook
    - nbconvert
    - nbformat
    - python
    - traitlets
    - pyyaml

about:
  home: https://github.com/ipython-contrib/IPython-notebook-extensions
  license:  Modified BSD License
  summary: 'Notebook extensions for the Jupyter/IPython notebook'

